FROM mcr.microsoft.com/dotnet/sdk:3.1  as build
WORKDIR webapp

EXPOSE 80
EXPOSE 62114

#COPY PROJECT FILES
COPY .src\BP.API.Web/*.csproj ./
RUN dotnet restore

#COPY EVERYTHING ELSE
COPY . . 
RUN dotnet publish -c Release -o out 

#Build image 
FROM mcr.microsoft.com/dotnet/sdk:3.1
WORKDIR /webapp
COPY --from=build /webapp/out .
ENTRYPOINT ["dotnet","BP.API.Application.dll"]